language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
    - '7.2'
    - '7.3'
    - '7.4'

jobs:
    include:
        - php: 7.1
          install: composer update --no-interaction --prefer-source --prefer-lowest
        - stage: coverage
          php: 7.4
          env: COVERAGE=true
          before_script:
            - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            - chmod +x ./cc-test-reporter
          script:
            - "phpunit --coverage-text --coverage-clover build/logs/clover.xml"
            - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT; fi

before_script:
    # disable xdebug if not coverage
    - if [[ $COVERAGE == "" ]]; then phpenv config-rm xdebug.ini; fi

install:
  - composer install --no-interaction --prefer-source

script:
    - make lint
    - make phpstan
    - make test

notifications:
    email: false
