language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
    - '7.0'
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4'

before_script:
    # disable xdebug if not coverage
    - if [[ $COVERAGE == "" ]]; then phpenv config-rm xdebug.ini; fi

install:
  - composer install --dev --no-interaction --prefer-source

script:
    - make lint
    - make phpstan
    - make test
